[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
directory = "/../backend/routes"
[build]
base = "frontend"
command = "npm run build"
publish = "build"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
