[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
[build]
command = "npm run build"
publish = "build"
functions = "server/netlify/functions"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.server/netlify/functions/api/:splat"
